Repository 100-hours-a-week/11-ellu-be, pull requests merged in 2025-05, with the labels that each got.

#13 fix: 로그인 시 응답 형식 수정(#12)
  src/main/java/com/ellu/looper/controller/AuthController.java
  src/main/java/com/ellu/looper/dto/AuthResponse.java
  src/main/resources/application.properties
Labels: fix

#18 feat: Project Schedule API 구현(#17)
  src/main/java/com/ellu/looper/controller/AuthController.java
  src/main/java/com/ellu/looper/controller/ProjectScheduleController.java
  src/main/java/com/ellu/looper/controller/ScheduleController.java
  src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleCreateRequest.java
  src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleCreateResponse.java
  src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleResponse.java
  src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleUpdateRequest.java
  src/main/java/com/ellu/looper/dto/schedule/ScheduleResponse.java
  src/main/java/com/ellu/looper/entity/Project.java
  src/main/java/com/ellu/looper/entity/ProjectMember.java
  src/main/java/com/ellu/looper/entity/ProjectSchedule.java
  src/main/java/com/ellu/looper/repository/AssigneeRepository.java
  src/main/java/com/ellu/looper/repository/ProjectRepository.java
  src/main/java/com/ellu/looper/repository/ProjectScheduleRepository.java
  src/main/java/com/ellu/looper/service/AuthService.java
  src/main/java/com/ellu/looper/service/ProjectScheduleService.java
  src/main/java/com/ellu/looper/service/ProjectService.java
  src/main/java/com/ellu/looper/service/ScheduleService.java
Labels: feat

#20 fix: API 응답 형식 수정에 따른 수정(#19)
  src/main/java/com/ellu/looper/controller/AuthController.java
  src/main/java/com/ellu/looper/dto/LoginResponse.java
  src/main/java/com/ellu/looper/dto/TokenRefreshResponse.java
  src/main/java/com/ellu/looper/service/AuthService.java
  src/main/java/com/ellu/looper/service/ProjectService.java
Labels: fix

#22 feat: FastAPI 연동을 위한 API 구현(#21)
  src/main/java/com/ellu/external/FastApiClient.java
  src/main/java/com/ellu/external/KakaoClient.java
  src/main/java/com/ellu/external/KakaoUserResponse.java
  src/main/java/com/ellu/looper/commons/PreviewHolder.java
  src/main/java/com/ellu/looper/config/WebClientConfig.java
  src/main/java/com/ellu/looper/controller/MeetingNoteController.java
  src/main/java/com/ellu/looper/controller/ProjectController.java
  src/main/java/com/ellu/looper/controller/WikiController.java
  src/main/java/com/ellu/looper/dto/MeetingNoteRequest.java
  src/main/java/com/ellu/looper/dto/MeetingNoteResponse.java
  src/main/java/com/ellu/looper/dto/TestResponse.java
  src/main/java/com/ellu/looper/dto/WikiRequest.java
  src/main/java/com/ellu/looper/service/AiService.java
  src/main/java/com/ellu/looper/service/FastApiService.java
  src/main/java/com/ellu/looper/service/ProjectService.java
  src/main/resources/application.properties
Labels: feat

#24 feat: S3이미지 저장 처리 및 환경변수 설정(#23)
  build.gradle
  src/main/java/com/ellu/looper/config/ProfileImageInitializer.java
  src/main/java/com/ellu/looper/config/S3Config.java
  src/main/java/com/ellu/looper/controller/AuthController.java
  src/main/java/com/ellu/looper/controller/ProfileImageController.java
  src/main/java/com/ellu/looper/entity/User.java
  src/main/java/com/ellu/looper/service/AuthService.java
  src/main/java/com/ellu/looper/service/ProfileImageService.java
  src/main/java/com/ellu/looper/service/S3Service.java
  src/main/java/com/ellu/looper/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/profile-images/profile_1.png
  src/main/resources/static/profile-images/profile_10.png
  src/main/resources/static/profile-images/profile_11.png
  src/main/resources/static/profile-images/profile_12.png
  src/main/resources/static/profile-images/profile_13.png
  src/main/resources/static/profile-images/profile_14.png
  src/main/resources/static/profile-images/profile_15.png
  src/main/resources/static/profile-images/profile_16.png
  src/main/resources/static/profile-images/profile_17.png
  src/main/resources/static/profile-images/profile_18.png
  src/main/resources/static/profile-images/profile_19.png
  src/main/resources/static/profile-images/profile_2.png
  src/main/resources/static/profile-images/profile_20.png
  src/main/resources/static/profile-images/profile_3.png
  src/main/resources/static/profile-images/profile_4.png
  src/main/resources/static/profile-images/profile_5.png
  src/main/resources/static/profile-images/profile_6.png
  src/main/resources/static/profile-images/profile_7.png
  src/main/resources/static/profile-images/profile_8.png
  src/main/resources/static/profile-images/profile_9.png
Labels: feat

#26 fix: API 응답 형식에 맞게 수정(#25)
  src/main/java/com/ellu/looper/controller/AuthController.java
  src/main/java/com/ellu/looper/controller/MeetingNoteController.java
  src/main/java/com/ellu/looper/controller/ProjectScheduleController.java
  src/main/java/com/ellu/looper/controller/ScheduleController.java
  src/main/java/com/ellu/looper/dto/MeetingNoteRequest.java
  src/main/java/com/ellu/looper/dto/ProjectCreateRequest.java
  src/main/java/com/ellu/looper/dto/UserResponse.java
  src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleResponse.java
  src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleUpdateRequest.java
  src/main/java/com/ellu/looper/dto/schedule/ScheduleCreateRequest.java
  src/main/java/com/ellu/looper/dto/schedule/ScheduleResponse.java
  src/main/java/com/ellu/looper/dto/schedule/ScheduleUpdateRequest.java
  src/main/java/com/ellu/looper/exception/GlobalExceptionHandler.java
  src/main/java/com/ellu/looper/exception/ValidationException.java
  src/main/java/com/ellu/looper/repository/ProjectScheduleRepository.java
  src/main/java/com/ellu/looper/service/AuthService.java
  src/main/java/com/ellu/looper/service/FastApiService.java
  src/main/java/com/ellu/looper/service/ProjectScheduleService.java
  src/main/java/com/ellu/looper/service/ProjectService.java
  src/main/java/com/ellu/looper/service/ScheduleService.java
  src/main/java/com/ellu/looper/service/UserService.java
Labels: fix

#30 feat: Swagger 설정 (#29)
  .env.template 
  .gitignore
  build.gradle
  src/main/java/com/ellu/looper/config/SecurityConfig.java
  src/main/java/com/ellu/looper/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: feat

#33 Fix/#31 include cookie create health endpoint fix request dtos
  src/main/java/com/ellu/looper/controller/AuthController.java
  src/main/java/com/ellu/looper/dto/AuthResponse.java
  src/main/java/com/ellu/looper/dto/LoginResponse.java
  src/main/java/com/ellu/looper/service/AuthService.java
  src/main/resources/application.yml
Labels: fix

#34 Feat/#32 wiki api
  src/main/java/com/ellu/looper/commons/PreviewHolder.java
  src/main/java/com/ellu/looper/controller/FastApiCallbackController.java
  src/main/java/com/ellu/looper/controller/ProjectController.java
  src/main/java/com/ellu/looper/controller/ProjectScheduleController.java
  src/main/java/com/ellu/looper/controller/ScheduleController.java
  src/main/java/com/ellu/looper/controller/WikiController.java
  src/main/java/com/ellu/looper/dto/ProjectResponse.java
  src/main/java/com/ellu/looper/dto/WikiRequest.java
  src/main/java/com/ellu/looper/entity/Project.java
  src/main/java/com/ellu/looper/service/FastApiService.java
  src/main/java/com/ellu/looper/service/ProjectService.java
Labels: feat

#38 fix: is_new_user 변수명 수정 (#37)
  src/main/java/com/ellu/looper/dto/AuthResponse.java
  src/main/resources/application.yml
Labels: fix

#49 fix: frontend에 반환될 회의록 응답 형식 수정
  src/main/java/com/ellu/looper/commons/PreviewHolder.java
  src/main/java/com/ellu/looper/service/ProjectService.java
  src/main/resources/static/profile-images/.DS_Store
Labels: fix

#50 fix: 프로젝트 일정 수정/삭제 endpoint 수정
  src/main/java/com/ellu/looper/controller/ProjectScheduleController.java
  src/main/java/com/ellu/looper/service/ProjectScheduleService.java
Labels: fix

#52 fix: 프로필이미지 파일에 presigned url 적용
  src/main/java/com/ellu/looper/service/ProfileImageService.java
  src/main/java/com/ellu/looper/service/ProjectService.java
  src/main/java/com/ellu/looper/service/S3Service.java
Labels: fix

#56 fix: meeting note dto id field 타입 수정
  src/main/java/com/ellu/looper/dto/MeetingNoteRequest.java
Labels: fix

#63 fix: 비동기 처리 추가 및 개발 환경 쿠키 설정 추가
  src/main/java/com/ellu/looper/commons/ScheduleHolder.java
  src/main/java/com/ellu/looper/config/SecurityConfig.java
  src/main/java/com/ellu/looper/controller/AuthController.java
  src/main/java/com/ellu/looper/controller/ProjectScheduleController.java
  src/main/java/com/ellu/looper/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ellu/looper/service/AuthService.java
  src/main/resources/application.yml
Labels: fix

#70 hotfix: async 처리
  src/main/java/com/ellu/looper/controller/AuthController.java
  src/main/java/com/ellu/looper/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ellu/looper/service/AuthService.java
  src/main/resources/application.yml
Labels: hotfix

#72 feat: 프로젝트 색상 필드 처리(#71)
  src/main/java/com/ellu/looper/dto/schedule/ProjectScheduleResponse.java
  src/main/java/com/ellu/looper/dto/schedule/ScheduleResponse.java
  src/main/java/com/ellu/looper/service/ProjectScheduleService.java
  src/main/java/com/ellu/looper/service/ProjectService.java
  src/main/java/com/ellu/looper/service/ScheduleService.java
Labels: feat

#82 Feat/#75 project domain
  src/main/java/com/ellu/external/FastApiClient.java
  src/main/java/com/ellu/looper/controller/AdminController.java
  src/main/java/com/ellu/looper/controller/UserController.java
  src/main/java/com/ellu/looper/dto/TestResponse.java
  src/main/java/com/ellu/looper/dto/UserProjection.java
  src/main/java/com/ellu/looper/entity/User.java
  src/main/java/com/ellu/looper/repository/UserRepository.java
  src/main/java/com/ellu/looper/service/AuthService.java
  src/main/java/com/ellu/looper/service/FastApiService.java
  src/main/java/com/ellu/looper/service/UserService.java
  src/main/java/com/ellu/looper/util/HangulUtil.java
Labels: feat

#83 feat: added project invitation exception & slight change in nickname live suggest logic
  src/main/java/com/ellu/looper/repository/UserRepository.java
  src/main/java/com/ellu/looper/service/ProjectService.java
  src/main/java/com/ellu/looper/service/UserService.java
Labels: feat

#85 feat: project detail view dto & project update logic revised
  src/main/java/com/ellu/looper/controller/ProjectController.java
  src/main/java/com/ellu/looper/dto/CreatorExcludedProjectResponse.java
  src/main/java/com/ellu/looper/dto/ProjectUpdateRequest.java
  src/main/java/com/ellu/looper/entity/ProjectMember.java
  src/main/java/com/ellu/looper/service/ProjectService.java
Labels: feat

#96 Feat/#95 kafka for notification
  build.gradle
  src/main/java/com/ellu/looper/commons/JsonConverter.java
  src/main/java/com/ellu/looper/commons/enums/InviteStatus.java
  src/main/java/com/ellu/looper/commons/enums/NotificationType.java
  src/main/java/com/ellu/looper/controller/NotificationController.java
  src/main/java/com/ellu/looper/controller/NotificationTestController.java
  src/main/java/com/ellu/looper/controller/SseController.java
  src/main/java/com/ellu/looper/dto/NotificationDto.java
  src/main/java/com/ellu/looper/entity/Notification.java
  src/main/java/com/ellu/looper/entity/NotificationTemplate.java
  src/main/java/com/ellu/looper/kafka/NotificationConsumer.java
  src/main/java/com/ellu/looper/kafka/NotificationProducer.java
  src/main/java/com/ellu/looper/kafka/dto/NotificationMessage.java
  src/main/java/com/ellu/looper/repository/NotificationRepository.java
  src/main/java/com/ellu/looper/repository/NotificationTemplateRepository.java
  src/main/java/com/ellu/looper/service/NotificationService.java
  src/main/java/com/ellu/looper/service/ProjectService.java
  src/main/java/com/ellu/looper/service/SseService.java
  src/main/resources/application.yml
Labels: feat

#100 maintenance: kafka 환경 변수 설정
  src/main/java/com/ellu/looper/kafka/NotificationConsumer.java
  src/main/java/com/ellu/looper/kafka/NotificationProducer.java
  src/main/resources/application.yml
Labels: chore
